KEYWORD: PROGRAMA, Línea 3
ID: factorial, Línea 3
ID: VarX, Línea 5
ASSIGNMENT: =, Línea 5
NUMERIC_LITERAL: 0x1, Línea 5
ID: VarY, Línea 7
ASSIGNMENT: =, Línea 7
NUMERIC_LITERAL: 0x0, Línea 7
KEYWORD: LEE, Línea 8
ID: Num, Línea 8
KEYWORD: REPITE, Línea 10
ID: NumVECES, Línea 10
ID: VarY, Línea 11
ASSIGNMENT: =, Línea 11
ID: VarY, Línea 11
ARITH_OP: +, Línea 11
NUMERIC_LITERAL: 0x1, Línea 11
ID: VarX, Línea 12
ASSIGNMENT: =, Línea 12
ID: VarX, Línea 12
ARITH_OP: *, Línea 12
ID: VarY, Línea 12
KEYWORD: FINREP, Línea 13
KEYWORD: IMPRIME, Línea 14
ID: Factorial, Línea 14
ID: de, Línea 14
KEYWORD: IMPRIME, Línea 15
ID: Num, Línea 15
KEYWORD: IMPRIME, Línea 16
ID: es, Línea 16
KEYWORD: IMPRIME, Línea 17
ID: VarX, Línea 17
KEYWORD: FINPROG, Línea 18
